# Change these first
# see https://github.com/superrr-vpn/status
owner: RealYalaSo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API
    url: https://api.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - kr6.yalaso.top
    url: http://kr6.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - gb7-lincolnshire.yalaso.top
    url: http://gb7-lincolnshire.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - jp8.yalaso.top
    url: http://jp8.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - 54360d94.yalaso.top
    url: http://54360d94.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - 2d582a2f.yalaso.top
    url: http://2d582a2f.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - us-2d0b03b7.yalaso.top
    url: http://us-2d0b03b7.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - hk-2d88c5eb.yalaso.top
    url: http://hk-2d88c5eb.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - au-b06145ad.yalaso.top
    url: http://au-b06145ad.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - ca-9e450b89.yalaso.top
    url: http://ca-9e450b89.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - ca-6790b1e9.yalaso.top
    url: http://ca-6790b1e9.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - nl-2501cb1d.yalaso.top
    url: http://nl-2501cb1d.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - ae-b0614281.yalaso.top
    url: http://ae-b0614281.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - us-2501d3f2.yalaso.top
    url: http://us-2501d3f2.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - ru-5bc1b64c.yalaso.top
    url: http://ru-5bc1b64c.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - de-053d2451.yalaso.top
    url: http://de-053d2451.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "5 * * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yalaso.top
  logoUrl: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  favicon: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  name: Status
  introTitle: "Status of Superrr VPN"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RealYalaSo/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
