# Change these first
owner: RealYalaSo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API
    url: https://api.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - sg3
    url: http://sg3.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - ca3
    url: http://ca3.yalaso.top/api/v1/ping
    method: POST
  - name: Node - de3
    url: http://de3.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - gb3
    url: http://gb3.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - jp3
    url: http://jp3.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - kr3
    url: http://kr3.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000
  - name: Node - us3
    url: http://us3.yalaso.top/api/v1/ping
    method: POST
    maxResponseTime: 2000

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "5 * * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yalaso.top
  logoUrl: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  name: Status
  introTitle: "Status of Superrr VPN"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RealYalaSo/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
