# Change these first
owner: RealYalaSo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: API
    url: https://api.yalaso.top/api/v1/ping
  - name: Node - sg1
    url: http://sg1.yalaso.top/api/v1/ping
  - name: Node - ca2
    url: http://ca2.yalaso.top/api/v1/ping
  - name: Node - de2
    url: http://de2.yalaso.top/api/v1/ping
  - name: Node - gb2
    url: http://gb2.yalaso.top/api/v1/ping
  - name: Node - jp2
    url: http://jp2.yalaso.top/api/v1/ping
  - name: Node - kr2
    url: http://kr2.yalaso.top/api/v1/ping
  - name: Node - us2
    url: http://us2.yalaso.top/api/v1/ping


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yalaso.top
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of Superrr VPN"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RealYalaSo/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
