# Change these first
# see https://github.com/superrr-vpn/status
owner: RealYalaSo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Yalaso Tech - Home page
    url: https://yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Home page old
    url: https://superrr-vpn.yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Home page
    url: https://turbo-max.yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Subscription
    url: https://turbo-max.yalaso.top/subscriptions.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Sign in
    url: https://turbo-max.yalaso.top/signin.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Terms
    url: https://turbo-max.yalaso.top/terms_of_service.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Policy
    url: https://turbo-max.yalaso.top/policy.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: API
    url: https://api.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: API Auth
    url: https://api.yalaso.top/api/v1/host/auth
    method: POST
    headers:
      - "Content-Type: application/json"
      - "User-Agent: GitHub Action"
    body: '{ "username": "username", "password": "password", "client_ip": "client_ip", "host_ip": "host_ip", "tx_id": "tx_id" }'
    expectedStatusCodes:
      - 200
      - 400
    maxResponseTime: 2000
  - name: Node - ae-b061422e.yalaso.top
    url: http://ae-b061422e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - au-ac69bc5e.yalaso.top
    url: http://au-ac69bc5e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-6790b1e9.yalaso.top
    url: http://ca-6790b1e9.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-ac6908f8.yalaso.top
    url: http://ca-ac6908f8.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-ac696997.yalaso.top
    url: http://ca-ac696997.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-053d2b7c.yalaso.top
    url: http://de-053d2b7c.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-592cc6ef.yalaso.top
    url: http://de-592cc6ef.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-8ba2aa51.yalaso.top
    url: http://de-8ba2aa51.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-ac689dc1.yalaso.top
    url: http://de-ac689dc1.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-555ad8aa.yalaso.top
    url: http://fr-555ad8aa.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-ace82156.yalaso.top
    url: http://fr-ace82156.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-ace9f2f2.yalaso.top
    url: http://fr-ace9f2f2.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-05082132.yalaso.top
    url: http://gb-05082132.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-053d3db7.yalaso.top
    url: http://gb-053d3db7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-6d4acbe0.yalaso.top
    url: http://gb-6d4acbe0.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-b24fa616.yalaso.top
    url: http://gb-b24fa616.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - jp-ac68603e.yalaso.top
    url: http://jp-ac68603e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - jp-ace941ce.yalaso.top
    url: http://jp-ace941ce.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - nl-ace92ebd.yalaso.top
    url: http://nl-ace92ebd.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - nl-ace93e8a.yalaso.top
    url: http://nl-ace93e8a.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-2d59e4d7.yalaso.top
    url: http://ru-2d59e4d7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-2d8102a9.yalaso.top
    url: http://ru-2d8102a9.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-b90442ee.yalaso.top
    url: http://ru-b90442ee.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-c257457d.yalaso.top
    url: http://ru-c257457d.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - sg-8ba2360b.yalaso.top
    url: http://sg-8ba2360b.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - sg-ac697c64.yalaso.top
    url: http://sg-ac697c64.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ua-8200ea14.yalaso.top
    url: http://ua-8200ea14.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-25092317.yalaso.top
    url: http://us-25092317.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2e159fc1.yalaso.top
    url: http://us-2e159fc1.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-480eb83f.yalaso.top
    url: http://us-480eb83f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-5cdf1ea7.yalaso.top
    url: http://us-5cdf1ea7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-607e6014.yalaso.top
    url: http://us-607e6014.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-68ed93e0.yalaso.top
    url: http://us-68ed93e0.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-aabb97b2.yalaso.top
    url: http://us-aabb97b2.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-ace99aa8.yalaso.top
    url: http://us-ace99aa8.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-ace9baad.yalaso.top
    url: http://us-ace9baad.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-ace9edc6.yalaso.top
    url: http://us-ace9edc6.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-acea110f.yalaso.top
    url: http://us-acea110f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "5 * * * *"
  uptime: "*/10 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yalaso.top
  logoUrl: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  favicon: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  name: Status
  introTitle: "Status of Superrr VPN"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RealYalaSo/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
